### ISSUE TITLE
Connection closed 1006 Going away all the time

### ISSUE THREAD

**Issue by mitar** [hharnisc/python-meteor#10]
I have a very simple program:

```
import MeteorClient

meteor = MeteorClient.MeteorClient('ws://127.0.0.1:3000/websocket')

def connected():
	print("[Meteor] Connected")

meteor.on('connected', connected)

def closed(code, reason):
	print("[Meteor] Connection closed {} {}".format(code, reason))

meteor.on('closed', closed)

def failed(data):
	print("[Meteor] Failed {}".format(data))

meteor.on('failed', failed)

def reconnected():
	print("[Meteor] Reconnected")

meteor.on('reconnected', reconnected)

meteor.connect()

import time
time.sleep(10000)
```

But I am getting all the time the following errors:

```
[Meteor] Connection closed 1006 Going away
[Meteor] Reconnected
[Meteor] Connection closed 1006 Going away
[Meteor] Reconnected
[Meteor] Connection closed 1006 Going away
[Meteor] Reconnected
```

Is that normal?

**Comment by ppettit** [comment]
hi  @mitar,

i've done a bunch of fixes over the last few days that i think might have got this sorted out (and #11).

could you try [my post_0.1.3_fixes branch of python-ddp](https://github.com/ppettit/python-ddp/tree/post_0.1.3_fixes) and [my post_0.1.3_fixes branch of python-meteor](https://github.com/ppettit/python-meteor/tree/post_0.1.3_fixes) and see it they solve your issues?

thanks,

paul.

**Comment by hharnisc** [comment]
I've merged in @ppettit (huge thank you!) changes and published them. To update the package run pip install -U python-meteor this should update both python-meteor and python-ddp to version 0.1.4
