### ISSUE TITLE
python-meteor not reconnecting on reload

### ISSUE THREAD

**Issue by fpaboim** [hharnisc/python-meteor#17]
Seems like the new version is not reconnecting after updating meteor code. Fixed by adding:
self.connected = True
to line 75 of MeteorClient, maybe this was left off when refactoring to take into account logging in. Don't know if anything else should be taken into account.

Cheers,
Francisco

**Comment by hharnisc** [comment]
It think it's actually related to the DDP version in the `python-ddp` package `python-meteor` depends on. I've got a pull request for it https://github.com/hharnisc/python-ddp/pull/4/ and I'll be reviewing/testing as soon as I can.

**Comment by hharnisc** [comment]
I've got https://github.com/hharnisc/python-ddp updated with the pull request and it's published to pypi. You can try out the latest version by upgrading.

```
$ pip install -U python-meteor
```

I'm going to close this out, feel free to open this back up or create a new issue if you're still having problems. Thanks again for the report!
