### ISSUE TITLE
Update maybe have bug

### ISSUE THREAD

**Issue by iascchen** [hharnisc/python-meteor#18]
Hi  hharnisc, your python-meteor is very cool.

I am learning meteor, and want to update data of Leaderboard with python-meteor.
I found, if I update as follow, the name of player will miss.:

    one_player = client.find_one('players', selector={'name': 'My Player'})
    client.update('players', {'_id': one_player["_id"]}, {'score':10}, callback=update_callback)

So I have to implement my function as follow, it works:

    one_player['score'] = 10
    client.update('players', {'_id': one_player["_id"]}, one_player, callback=update_callback)

I think the first method is better. 
Is it a bug?

**Comment by hharnisc** [comment]
Not sure by this example. Its possible the contents of `one_player` are not what you're expecting, though it's hard to tell. Could you post a complete example I can run locally and try it out?

Note that the update method is calling the `Meteor server method` directly - https://github.com/hharnisc/python-meteor/blob/master/MeteorClient.py#L259

**Comment by iascchen** [comment]
# _*_ coding:utf-8 _*_

    import time
    
    from MeteorClient import MeteorClient
    
    client = MeteorClient('ws://127.0.0.1:3000/websocket')
    
    # Status
    
    def subscribed(subscription):
        print '* SUBSCRIBED {}'.format(subscription)
    
    
    def unsubscribed(subscription):
        print '* UNSUBSCRIBED {}'.format(subscription)
    
    
    def added(collection, id, fields):
        print '* ADDED {} {}'.format(collection, id)
        for key, value in fields.items():
            print '  - FIELD {} {}'.format(key, value)
    
        # query the data each time something has been added to
        # a collection to see the data `grow`
        all_lists = client.find('players', selector={})
        print 'Lists: {}'.format(all_lists)
        print 'Num lists: {}'.format(len(all_lists))
    
    
        # if collection == 'list' you could subscribe to the list here
        # with something like
        # client.subscribe('todos', id)
        # all_todos = client.find('todos', selector={})
        # print 'Todos: {}'.format(all_todos)
    
    
    def changed(collection, id, fields, cleared):
        print '* CHANGED {} {}'.format(collection, id)
        for key, value in fields.items():
            print '  - FIELD {} {}'.format(key, value)
        for key, value in cleared.items():
            print '  - CLEARED {} {}'.format(key, value)
    
    
    def removed(collection, id):
        print '* REMOVED {} {}'.format(collection, id)
    
    
    def connected():
        print '* CONNECTED'
    
    
    # Callback
    
    def subscription_callback(error):
        if error:
            print error
    
    
    def insert_callback(error, data):
        if error:
            print error
            return
        print data
    
    
    def update_callback(error, data):
        if error:
            print error
            return
        print data
    
    
    def remove_callback(error, data):
        if error:
            print error
            return
        print data
    
    # Events
    
    client.on('subscribed', subscribed)
    client.on('unsubscribed', unsubscribed)
    client.on('connected', connected)
    client.on('added', added)
    client.on('changed', changed)
    client.on('removed', removed)
    
    client.connect()
    client.subscribe('players')
    
    all_player = client.find('players', selector={})
    print all_player
    
    print '#################'
    
    one_player = client.find_one('players', selector={'name': 'My Player'})
    
    if one_player is None:
        client.insert('players', {'name': 'My Player', 'score': 0}, callback=insert_callback)
        print one_player
    elif one_player['score'] == 0:
        # follow commented sentence will change player's name to ""
        # client.update('players', {'_id': one_player["_id"]}, {'score':10}, callback=update_callback)

        # follow is OK
        one_player['score'] = 10
        client.update('players', {'_id': one_player["_id"]}, one_player, callback=update_callback)

        print one_player
    else:
        client.remove('players', {'_id': one_player["_id"]},
                      callback=remove_callback)  # (sort of) hacky way to keep the client alive

**Comment by fpaboim** [comment]
you're missing $set on update, maybe?

    client.update('players', {'_id': one_player["_id"]}, { '$set': {'score':10}}, callback=update_callback)

**Comment by hharnisc** [comment]
Yep @fpaboim is correct. When you don't use `$set`, the `update` function will blow away the whole document and replace it with the document provided. This is mongoDB (not a bug) - http://docs.mongodb.org/manual/reference/method/db.collection.update/

**Comment by iascchen** [comment]
Yes, I missed the {'$set': {'score': 10}}, thanks very much.
