### ISSUE TITLE
Subscription name not working

### ISSUE THREAD

**Issue by hedaro** [hharnisc/python-meteor#27]
I am trying to subscribe to a collection in my meteor app, but it seems like the publication name is not sent.
I have my publication and my client subscription as follows

```
// Meteor app
Meteor.publish('videos', function () {
  return Videos.find();
});

#python script
client.subscribe('videos', callback=subscription_callback)
```

But when i call client.find('vdieos') it returns empty.
Whoever if i make a default publish without name

```
Meteor.publish(null, function () {
  return Videos.find();
});
```

It always subscribes no matter what name i pass to the function.

Edit:
Also i know it doesn't subscribe because when it does the added event fires, which happens with the null publish but not with a named publish.

**Comment by marcosdiez** [comment]
I might be having the same issue.

Except with "users".

```
    for collection in [ "users" , "some_name", "some_other_name"]:
        result = client.find(collection)
        if result is not None:
            print "{} - {}".format(collection, result)
        client.subscribe(collection, callback=subscription_callback)
```

Both find() and subscribe() return something for "users".
find(), by the way, returns only the user to which I logged in.

**Comment by marcosdiez** [comment]
I found out the issue. It is not a bug in the library.
On Meteor one must subscribe to some collections before the login.

Here is how I solved the problem on my side:

a) open the meteor website with chrome
b) go to the developer tools/Network/WS
c) click on the websocket (on the left)
d) subscribe to the same things that chorme does, on the same order

things will work.
